branches:
  except:
  - release

sudo: required

matrix:
  include:
    - os: osx
      env: BUILD_NAME=macosx
      compiler: clang
      language: cpp
      osx_image: xcode7.3
    - os: osx
      env: BUILD_NAME=ios
      compiler: clang
      language: cpp
      osx_image: xcode7.3
    - os: linux
      env: BUILD_NAME=debian
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=ubuntu
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=raspberry_pi
      compiler: gcc
      language: cpp
      dist: trusty
    - env: BUILD_NAME=android
      language: android


android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
#    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

env:
  global:
  #encrypted PRORAB_GIT_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "AcMDkVUsSFBKob8ijJ48ef4fqtpelNtMnYsJHB/wn0V+ABaVePiKzO4M10SnLtQNyTb5XbUe0+9uENSJhqwa6jVWLEgRvgTifXqPHql9Ymz5CcfxbR02d+DuJCgSfMs9CPnJB3TqJ5olPeozsuUkupui0jRd5uBZTNZ7nPkivvZVkhS21ZhDMmGEHtS6cUUx7kRbVRRBRHhIAYjxyS9bUQJIpcPk+Rs07vO0vaoF1jqrsE3ywGso0ICD76MwCUnxEMvSTd/qnRJTNInBU4AjGSna4nw8DvRcbOUPE9to2YSpv+kZiiV4fzSk61CjlV1qA0vVYtHfsAWLm69WziPwRN8crg4+gJx0zRGr9kV0gWDTM/BpgSouLy2qNX+xOPrjIfbkU8tClUpXXNg5812+1YQIVaG0rkv3sUCDrrq1yGj+ZNomlw3n6w1yuBbRIvn8SH8ZEKMXkzp7np79aDgF4TPs6EvyGnU/TnXTvpQpug4LYmoW8uRo+t62ZP1yDrg/1AEDAb32k8LSS3k4kheklS92X/vbYF4hurZJQBjzl26R/RUdCZLrwee40ogxD5ch/8pYWB45mTRXOJnBIt/notAYJ5/9LqzB20KXzzpUPH7dgyj4/+6Cqe+Jbph09PEvlfsQ9ZlEFqsMK2fOHcPNUK2RsellYPVThO+h9ohRihM="
  - PRORAB_GIT_USERNAME=igagis
  - USE_ANDROID_NDK_VERSION=15c
  - linuxDependencies="debhelper prorab prorab-extra myci doxygen libutki-dev"


before_install:
- if [ "$BUILD_NAME" == "macosx" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&
    
    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab prorab-extra myci libutki;
  fi
# Force bundler 1.12.5 because version 1.13 has issues, see https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617
- if [ "$BUILD_NAME" == "ios" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&
    
    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install myci &&
    
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$PRORAB_GIT_USERNAME:$PRORAB_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=ios;
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    echo "deb https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq myci;
  fi
- if [ "$BUILD_NAME" == "debian" ]; then
    echo "deb http://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild myci prorab prorab-extra debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg1,dirmngr,build-essential stretch /srv/chroot/deb-amd64 http://httpredir.debian.org/debian &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /srv/chroot/deb-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/deb-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo chroot /srv/chroot/deb-amd64 ln -s /usr/bin/gpg1 /usr/bin/gpg;
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    echo "deb http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild myci prorab prorab-extra debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg,dirmngr,build-essential xenial /srv/chroot/ubu-amd64 http://archive.ubuntu.com/ubuntu/ &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /srv/chroot/ubu-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/ubu-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    echo "deb http://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq myci;
    sudo myci-make-raspberry-chroot.sh /srv/chroot/rasp-armhf &&
    echo "deb http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies g++ &&
    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
  fi

before_script:
  # download and install android NDK
  - if [ "$BUILD_NAME" == "android" ]; then
      export TERM=dumb &&
      curl -L https://dl.google.com/android/repository/android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip -O &&
      unzip ./android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip > /dev/null &&
      rm android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip &&
      export ANDROID_NDK_HOME=`pwd`/android-ndk-r$USE_ANDROID_NDK_VERSION &&
      export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME" &&
      export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64" &&
      export PATH=$PATH:${ANDROID_NDK_HOME} &&
      env;
    fi
  - if [ "$BUILD_NAME" == "ios" ]; then
      curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
      chmod +x XcodeProjAdder &&
      (cd ios && ../XcodeProjAdder -XCP tests.xcodeproj -SCSV `echo $(find ../src -type f -name *.cpp) | sed -n -e 's/ /,/gp'`);
    fi

script:
- if [ "$BUILD_NAME" == "debian" ]; then
    myci-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d stretch-amd64-sbuild --run-lintian --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    myci-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d xenial-amd64-sbuild --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    make &&
    make test;
  fi
- if [ "$BUILD_NAME" == "ios" ]; then
    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && myci-deb-prepare.sh" &&
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && dpkg-buildpackage -us -uc";
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.pom.in &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi

before_deploy:
  - myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` travis_bintray_*.json.in

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_deb.json
  user: igagis
  key:
    secure: "Lar4sKMpCwHDA35DYmkAxAFcOMCaEb7pq4P7LoQnn7c9pxH5P3S6bZB0HOtJS8HjsJBb2iQfQf2nUp58SGJDQ3WeqX+b2OUHSQ0ySg9Akf7IWtpqA6HzpJC0otLCz3IqUo7kG9/tRTZkQZ53gqsVQjTA9nfFouwaNMDSezGGm2OJRg1ws9/fWlL2ib+/K55dbKTUUMsScpYSLcW6qoVux7q3Toy/iNdznASWha1ER7kXxQqD05UY6OZrFhPF1XoK/gLHD6ONtF9bMm9dfyk/IubwZ5Xj4ACp/7bK2tT3iEiAuNj31IKR+5uFl6jV9+Z+F6RVYq85fjm9VUqLfphlj12u4g08sWmK1as2elUk8Y/bNJuL6vLQnKywkQKDSKUrYiVxssyPOCNtxFKEmj1qUrAyKCeyVmgGYMFYwsRihCcccehoVVnTv0QfmKu0J2F876olHT8BzbXrlZWxnuD7117hUVGDuHWFI73wVF0gQ6ovq1lfVI8VFGtJG1QuS7kqb+3Gky5TC9j1dcASNWa8/pZwTz5if6d1pOQOqbVY4c1B/ZkBTDYAec/sHdxPlUbcHCPzc9r8ikbK0pl8Nfvpebf8q6xKUVe0iAwmhNXGWb8BD4V3IjdZCaIjVUYqV0ucJWD2oORABmJoZiDtiKcokgC72jU4bS76h5/mjTOMSlU="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = ubuntu
  file: travis_bintray_ubu.json
  user: igagis
  key:
    secure: "Lar4sKMpCwHDA35DYmkAxAFcOMCaEb7pq4P7LoQnn7c9pxH5P3S6bZB0HOtJS8HjsJBb2iQfQf2nUp58SGJDQ3WeqX+b2OUHSQ0ySg9Akf7IWtpqA6HzpJC0otLCz3IqUo7kG9/tRTZkQZ53gqsVQjTA9nfFouwaNMDSezGGm2OJRg1ws9/fWlL2ib+/K55dbKTUUMsScpYSLcW6qoVux7q3Toy/iNdznASWha1ER7kXxQqD05UY6OZrFhPF1XoK/gLHD6ONtF9bMm9dfyk/IubwZ5Xj4ACp/7bK2tT3iEiAuNj31IKR+5uFl6jV9+Z+F6RVYq85fjm9VUqLfphlj12u4g08sWmK1as2elUk8Y/bNJuL6vLQnKywkQKDSKUrYiVxssyPOCNtxFKEmj1qUrAyKCeyVmgGYMFYwsRihCcccehoVVnTv0QfmKu0J2F876olHT8BzbXrlZWxnuD7117hUVGDuHWFI73wVF0gQ6ovq1lfVI8VFGtJG1QuS7kqb+3Gky5TC9j1dcASNWa8/pZwTz5if6d1pOQOqbVY4c1B/ZkBTDYAec/sHdxPlUbcHCPzc9r8ikbK0pl8Nfvpebf8q6xKUVe0iAwmhNXGWb8BD4V3IjdZCaIjVUYqV0ucJWD2oORABmJoZiDtiKcokgC72jU4bS76h5/mjTOMSlU="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = raspberry_pi
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "Lar4sKMpCwHDA35DYmkAxAFcOMCaEb7pq4P7LoQnn7c9pxH5P3S6bZB0HOtJS8HjsJBb2iQfQf2nUp58SGJDQ3WeqX+b2OUHSQ0ySg9Akf7IWtpqA6HzpJC0otLCz3IqUo7kG9/tRTZkQZ53gqsVQjTA9nfFouwaNMDSezGGm2OJRg1ws9/fWlL2ib+/K55dbKTUUMsScpYSLcW6qoVux7q3Toy/iNdznASWha1ER7kXxQqD05UY6OZrFhPF1XoK/gLHD6ONtF9bMm9dfyk/IubwZ5Xj4ACp/7bK2tT3iEiAuNj31IKR+5uFl6jV9+Z+F6RVYq85fjm9VUqLfphlj12u4g08sWmK1as2elUk8Y/bNJuL6vLQnKywkQKDSKUrYiVxssyPOCNtxFKEmj1qUrAyKCeyVmgGYMFYwsRihCcccehoVVnTv0QfmKu0J2F876olHT8BzbXrlZWxnuD7117hUVGDuHWFI73wVF0gQ6ovq1lfVI8VFGtJG1QuS7kqb+3Gky5TC9j1dcASNWa8/pZwTz5if6d1pOQOqbVY4c1B/ZkBTDYAec/sHdxPlUbcHCPzc9r8ikbK0pl8Nfvpebf8q6xKUVe0iAwmhNXGWb8BD4V3IjdZCaIjVUYqV0ucJWD2oORABmJoZiDtiKcokgC72jU4bS76h5/mjTOMSlU="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = android
  file: travis_bintray_android.json
  user: igagis
  key:
    secure: "Lar4sKMpCwHDA35DYmkAxAFcOMCaEb7pq4P7LoQnn7c9pxH5P3S6bZB0HOtJS8HjsJBb2iQfQf2nUp58SGJDQ3WeqX+b2OUHSQ0ySg9Akf7IWtpqA6HzpJC0otLCz3IqUo7kG9/tRTZkQZ53gqsVQjTA9nfFouwaNMDSezGGm2OJRg1ws9/fWlL2ib+/K55dbKTUUMsScpYSLcW6qoVux7q3Toy/iNdznASWha1ER7kXxQqD05UY6OZrFhPF1XoK/gLHD6ONtF9bMm9dfyk/IubwZ5Xj4ACp/7bK2tT3iEiAuNj31IKR+5uFl6jV9+Z+F6RVYq85fjm9VUqLfphlj12u4g08sWmK1as2elUk8Y/bNJuL6vLQnKywkQKDSKUrYiVxssyPOCNtxFKEmj1qUrAyKCeyVmgGYMFYwsRihCcccehoVVnTv0QfmKu0J2F876olHT8BzbXrlZWxnuD7117hUVGDuHWFI73wVF0gQ6ovq1lfVI8VFGtJG1QuS7kqb+3Gky5TC9j1dcASNWa8/pZwTz5if6d1pOQOqbVY4c1B/ZkBTDYAec/sHdxPlUbcHCPzc9r8ikbK0pl8Nfvpebf8q6xKUVe0iAwmhNXGWb8BD4V3IjdZCaIjVUYqV0ucJWD2oORABmJoZiDtiKcokgC72jU4bS76h5/mjTOMSlU="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $BUILD_NAME = macosx
- provider: script
  skip_cleanup: true
  script: rvm 2.3.3 do myci-deploy-cocoapods.sh -r igagis
  on:
    tags: true
    condition: $BUILD_NAME = ios
